version: '3'
services:
  neo4j:
    image: abdel99/fraudneo4jv1:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/ilisi2
      NEO4J_dbms_logs_debug_level: DEBUG